export const ADD_CHARACTER = "ADD_CHARACTER";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const SEARCH_BY_ID = "SEARCH_BY_ID"
export const SEARCH_RANDOM ="SEARCH_RANDOM"
export const SEARCH_BY_NAME = "SEARCH_BY_NAME"
export const GET_ALL_CHARACTER = "GET_ALL_CHARACTER"
export const GET_DETAIL_CHARACTER = "GET_DETAIL_CHARACTER"
export const USE_ALL_CHAR_AUX ="USE_ALL_CHAR_AUX "